version: '3.8'
services:
  test-db:
    image: postgres
    container_name: game-management
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest